---
# tasks file for app-tier
- name: install "{{ payload }}"
  yum:
    name: "{{ payload }}"
    state: latest

- name: create "{{ payload }}" root directory
  file:
    path: "{{ web_root }}"
    state: directory

- name: start and enable "{{ payload }}" at reboot
  service:
    name: "{{ payload }}"
    state: started
    enabled: yes
    
- name: Create index file
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    mode: 0644
  notify: restart "{{ payload }}"

    
